Improved the _start()  method in the sysv initscript. Until now a start of the consul agent followed by a reload will interrupt the start process and the consul agent will be stopped You can simply reproduce this by calling: /etc/init.d/consul restart; /etc/init.d/consul reload; /etc/init.d/consul status
 This is likely to happen if you make a change in a wrapper cookbook that triggeres a consul restart and another change which triggeres a consul reload. Your consul agent will be stopped afterwards.

  To fix this this change will make sure the consul service is started before leaving the _start() method.

diff --git a/templates/default/sysvinit.service.erb b/templates/default/sysvinit.service.erb
--- a/templates/default/sysvinit.service.erb
+++ b/templates/default/sysvinit.service.erb
@@ -32,10 +32,27 @@ export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 _start() {
   touch $logfile
   chown $user $logfile
+  echo "Starting consul"
   start-stop-daemon --start --quiet --background \
       --pidfile $pidfile<% unless @pid_file_external %> --make-pidfile<% end %> \
       --chuid $user --chdir "<%= @directory %>" \
       --startas /bin/bash -- -c "exec $exec <%= @daemon_options %> >> $logfile 2>&1"
+
+  echo -n "Waiting for consul daemon to be listening..."
+  for i in `seq 1 30`; do
+    if ! start-stop-daemon --quiet --stop --test --pidfile $pidfile --user $user; then
+      echo " FAIL: consul process died"
+      return 2
+    fi
+    if "$exec" info >/dev/null; then
+      echo " OK"
+      return 0
+    fi
+    echo -n .
+    sleep 1
+  done
+  echo " FAIL: consul process is alive, but is not listening."
+  return 2
 }
 
 _stop() {
