moved hook to _wait_for_listening function

diff --git a/templates/default/sysvinit.service.erb b/templates/default/sysvinit.service.erb
--- a/templates/default/sysvinit.service.erb
+++ b/templates/default/sysvinit.service.erb
@@ -38,21 +38,7 @@ _start() {
       --chuid $user --chdir "<%= @directory %>" \
       --startas /bin/bash -- -c "exec $exec <%= @daemon_options %> >> $logfile 2>&1"
 
-  echo -n "Waiting for consul daemon to be listening..."
-  for i in `seq 1 30`; do
-    if ! _status_q; then
-      echo " FAIL: consul process died"
-      return 2
-    fi
-    if "$exec" info >/dev/null; then
-      echo " OK"
-      return 0
-    fi
-    echo -n .
-    sleep 1
-  done
-  echo " FAIL: consul process is alive, but is not listening."
-  return 2
+  _wait_for_listening
 }
 
 _stop() {
@@ -121,6 +107,25 @@ _restart() {
 
 _status_q() {
     _status >/dev/null 2>&1
+}
+
+_wait_for_listening() {
+  echo -n "Waiting for consul daemon to be listening..."
+  for i in `seq 1 30`; do
+    # if ! start-stop-daemon --quiet --stop --test --pidfile $pidfile --user $user; then
+    if ! _status_q; then
+      echo " FAIL: consul process died"
+      return 2
+    fi
+    if "$exec" info >/dev/null; then
+      echo " OK"
+      return 0
+    fi
+    echo -n .
+    sleep 1
+  done
+  echo " FAIL: consul process is alive, but is not listening."
+  return 2
 }
 
 case "$1" in
